# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1, verbose_name='Genero Animal')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestacion', models.DateField(verbose_name='Fecha de Gestacion')),
                ('fecha_parto', models.DateField(verbose_name='Fecha de parto')),
                ('numero_partos', models.IntegerField(verbose_name='Numero de partos')),
                ('cantidad_por_parto', models.IntegerField(verbose_name='Cantidad de animales por parto')),
                ('status', models.BooleanField(default=True)),
                ('cerdo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cerdo.Cerdos')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
