# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerdo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunas',
            name='cerdo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cerdo.Cerdos'),
        ),
    ]
